name: Daily YouTube Fetch

on:
  schedule:
    # GitHub Actions 使用 UTC；LA 00:00 ≈ 夏令时 07:00、冬令时 08:00
    - cron: "0 7 * * *"
    - cron: "0 8 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: daily-youtube-fetch
  cancel-in-progress: false

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch_stats.py
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          # 如需代理：在仓库 Secrets 配好后再打开
          # HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}
          # HTTP_PROXY: ${{ secrets.HTTP_PROXY }}
        run: python fetch_stats.py

      - name: Commit & push data/history.csv (force-with-lease)
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          set -eux
          git status
          git add data/history.csv || true
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "chore: daily fetch (auto)"
          # 与远端对齐，避免 non-fast-forward
          git fetch origin main
          # 先尝试 rebase；若冲突，回滚 rebase 并用 ours 合并兜底（保留本次生成的 CSV）
          git rebase origin/main || (git rebase --abort && git merge -s ours origin/main -m "merge origin/main (ours for CSV)")
          # 推送（带 --force-with-lease，安全强推）
          git push --force-with-lease origin HEAD:main
