name: Daily YouTube Fetch

on:
  schedule:
    - cron: "0 */2 * * *"  # 每隔 2 小时整点执行（UTC）
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: daily-youtube-fetch
  cancel-in-progress: false

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch_stats.py
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          # 如需代理：在 Secrets 配好后再放开
          # HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}
          # HTTP_PROXY: ${{ secrets.HTTP_PROXY }}
        run: python fetch_stats.py

      - name: Commit & push data/history.csv (rebase, then force-with-lease)
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          set -eux
          git status
          git add data/history.csv || true
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "chore: daily fetch (auto)"
          git fetch origin main
          git rebase origin/main || (git rebase --abort && git merge -s ours origin/main -m "merge origin/main (ours for CSV)")
          git push --force-with-lease origin HEAD:main
